### ISSUE TITLE
Add a github project library example that is tree-shakeable?

### ISSUE THREAD

**Issue by kunukn** [mikeheddes/mikeheddes-website#40]
Regarding this article
https://mikeheddes.nl/articles/tree-shaking-nodejs-library

Would you mind adding or linking to a code project example?

It would be really nice to be able to github clone a project and having a boiler-plate example of a tree shake-able library.

**Comment by mikeheddes** [comment]
He @kunukn, I am so sorry for the late response. I didn't get any notification about your issue. I happened to checkout my open issues now and saw it. 

The project that I did that research on is private and from a company I used to work for. I am not sure how helpful a boiler-plate repository will be. From what I found it is important that the following three requirements are met:
1. Use ES6 module syntax, import and export (also after the code is transpiled).
1. Separate code in different files (not bundled, set preserveModules: true in Rollup config).
1. Set the sideEffects flag in package.json.

So an boiler plate would look something like:
```js
// src/index.js
// assuming these files exist and have a default export
export { default as SomeThing } from './something.js'
export { default as AnotherThing } from './anotherThing.js'
```

```js
// package.json
{
    ...
    sideEffects: false, // assume you don't have side effects in your code
    ...
}
```

```js
// rollup.config.js
import { peerDependencies, dependencies } from './package.json';

// Outputs ES6 modules to separate files
// For compatibility it is also possible to output multiple targets/bundles e.g. umd
// for a umd bundle preserveModules should be false because 
// tree shaking doesn't work with umd bundles
export default {
    ...
    preserveModules: true, // important!
    external: [...Object.keys(dependencies), ...Object.keys(peerDependencies)],
    output: { dir: 'dist', format: 'es' },
    ...
  },

```
